### PR TITLE
Add RTD css templates

### LINKED ISSUE #4: Add Docs by default
Related issue: https://github.com/nexB/scancode-toolkit/issues/2345

### PR DESCRIPTION
**Pull request by AyanSinhaMahapatra**
Closes #4 

Adds changes to conf.py and html template theme_overrides.css
created by @johnmhoran

Signed-off-by: Ayan Sinha Mahapatra <ayansmahapatra@gmail.com>

### CODE REVIEW

**Review by johnmhoran — COMMENTED** [review]
LGTM @AyanSinhaMahapatra  👍

**Comment by AyanSinhaMahapatra** [comment]
@johnmhoran I'm not sure this works though, see https://nexb-skeleton.readthedocs.io/en/add-rtd-templates/

Did I mess something up while adding?

**Comment by AyanSinhaMahapatra** [comment]
Console says `Failed to load resource: net::ERR_FILE_NOT_FOUND  theme_overrides.css:1`

**Comment by AyanSinhaMahapatra** [comment]
Nvm, this works now. Merging!

**Pull request merged**
