### PR TITLE
Configure for path with spaces on windows

### PR DESCRIPTION
**Pull request by chinyeungli**
We need to update the script to support spaces in the installation path.
Background can be found at https://github.com/nexB/aboutcode-toolkit/issues/489

### CODE REVIEW

**Review by pombredanne — CHANGES_REQUESTED** [review]
Thanks... this is LGTM overall, but I do not have enough Windows savvyness to ensure this works in all cases. Can you confirm that https://github.com/nexB/aboutcode-toolkit/issues/489 is a proper solution including for ScanCode toolkit?  If you could do a tests with this updated files locally in a SCTK checkout?

**Comment by chinyeungli** [comment]
Confirmed I've the same error for the current `configure.bat`
```
C:\Users\thoma\Desktop\tmp\New folder>git clone git@github.com:nexB/scancode-toolkit.git
Cloning into 'scancode-toolkit'...
remote: Enumerating objects: 268287, done.
remote: Counting objects: 100% (46590/46590), done.
remote: Compressing objects: 100% (18320/18320), done.
remote: Total 268287 (delta 23091), reused 45475 (delta 22427), pack-reused 221697
Receiving objects: 100% (268287/268287), 534.86 MiB | 6.93 MiB/s, done.
Resolving deltas: 100% (164505/164505), done.
Checking out files: 100% (87562/87562), done.

C:\Users\thoma\Desktop\tmp\New folder>cd scancode-toolkit

C:\Users\thoma\Desktop\tmp\New folder\scancode-toolkit>configure
The system cannot find the file specified.
The system cannot find the path specified.
The system cannot find the path specified.
usage: virtualenv [--version] [--with-traceback] [-v | -q] [--read-only-app-data] [--app-data APP_DATA] [--reset-app-data] [--upgrade-embed-wheels] [--discovery {builtin}] [-p py] [--try-first-with py_exe]
                  [--creator {builtin,cpython3-win,venv}] [--seeder {app-data,pip}] [--no-seed] [--activators comma_sep_list] [--clear] [--no-vcs-ignore] [--system-site-packages] [--copies] [--no-download | --download]
                  [--extra-search-dir d [d ...]] [--pip version] [--setuptools version] [--wheel version] [--no-pip] [--no-setuptools] [--no-wheel] [--no-periodic-update] [--prompt prompt] [-h]
                  dest
virtualenv: error: unrecognized arguments: folder\scancode-toolkit\\venv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file C:\Users\thoma\Desktop\tmp\New
Warning: folder\scancode-toolkit\\venv\virtualenv.pyz: No such file or
Warning: directory
  0 10.6M    0  1371    0     0   1584      0  1:57:12 --:--:--  1:57:12  1584
curl: (23) Failure writing output to destination

C:\Users\thoma\Desktop\tmp\New folder\scancode-toolkit>
```
WIth the latest `configure.bat` that I just pushed today, everything went fine. (Both aboutcode-tk and scancode-tk)

**Review by pombredanne — APPROVED** [review]
@chinyeungli Thank you!

**Comment by mjherzog** [comment]
It is not unreasonable to not support spaces in a path or file name so long as we clearly document that requirement.

**Pull request merged**
