### PR TITLE
Replace packaging with packvers in src/scripts

### PR DESCRIPTION
**Pull request by swastkk**
Resolves https://github.com/nexB/skeleton/issues/70
and https://github.com/nexB/python-inspector/pull/109#discussion_r1062697223
Signed-off-by: swastik <swastkk@gmail.com>

### CODE REVIEW

**Comment by swastkk** [comment]
@pombredanne review please :")

**Review by pombredanne — CHANGES_REQUESTED** [review]
Thank you!
Please add also packvers to https://github.com/nexB/skeleton/blob/main/etc/scripts/requirements.txt

**Comment by swastkk** [comment]
> Thank you! Please add also packvers to https://github.com/nexB/skeleton/blob/main/etc/scripts/requirements.txt

Done ✔️

**Review by pombredanne — APPROVED** [review]
LGTM. Merging! Thanks!

**Review by pombredanne — CHANGES_REQUESTED** [review]
Actually, one last change if you do not mind:
Can you squash and update your commit message?
Thanks!

**Comment by swastkk** [comment]
> Actually, one last change if you do not mind: Can you squash and update your commit message? Thanks!

okay now?

**Review by pombredanne — APPROVED** [review]
Thanks!
we want to have one empty line after the subject line for next time. I am merging now.

**Pull request merged**
